import { Router } from 'express';
import PDFDocument from 'pdfkit';
import db from '../../config/database.js';
import { authenticate } from '../../middleware/auth.js';

const router = Router();

// List reports (scans with results)
router.get('/', authenticate, (req, res) => {
  const scans = db.prepare(
    'SELECT * FROM scans WHERE user_id = ? AND status = "completed" ORDER BY completed_at DESC'
  ).all(req.user.id);
  res.json({ reports: scans });
});

// Generate PDF report
router.get('/:scanId/pdf', authenticate, (req, res) => {
  const scan = db.prepare('SELECT * FROM scans WHERE id = ? AND user_id = ?').get(req.params.scanId, req.user.id);
  if (!scan) return res.status(404).json({ error: 'Scan not found' });

  const vulnerabilities = db.prepare(
    'SELECT * FROM vulnerabilities WHERE scan_id = ? ORDER BY cvss_score DESC'
  ).all(req.params.scanId);

  const doc = new PDFDocument({ margin: 50 });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=webfort-report-${scan.id.slice(0, 8)}.pdf`);
  doc.pipe(res);

  // Header
  doc.fontSize(28).fillColor('#6366f1').text('WebFort', { align: 'center' });
  doc.fontSize(12).fillColor('#64748b').text('Enterprise Vulnerability Scanner', { align: 'center' });
  doc.moveDown(2);

  // Scan Details
  doc.fontSize(18).fillColor('#1e293b').text('Scan Report');
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#475569');
  doc.text(`Target: ${scan.target_url}`);
  doc.text(`Scan Type: ${scan.scan_type}`);
  doc.text(`Date: ${scan.completed_at || scan.created_at}`);
  doc.text(`Pages Scanned: ${scan.pages_scanned}`);
  doc.moveDown();

  // Summary
  doc.fontSize(14).fillColor('#1e293b').text('Vulnerability Summary');
  doc.moveDown(0.5);
  doc.fontSize(10).fillColor('#475569');
  doc.text(`Total Vulnerabilities: ${scan.total_vulnerabilities}`);
  doc.fillColor('#ef4444').text(`Critical: ${scan.critical_count}`);
  doc.fillColor('#f97316').text(`High: ${scan.high_count}`);
  doc.fillColor('#eab308').text(`Medium: ${scan.medium_count}`);
  doc.fillColor('#3b82f6').text(`Low: ${scan.low_count}`);
  doc.fillColor('#6b7280').text(`Info: ${scan.info_count}`);
  doc.moveDown(2);

  // Vulnerabilities
  if (vulnerabilities.length > 0) {
    doc.fontSize(14).fillColor('#1e293b').text('Detailed Findings');
    doc.moveDown();

    vulnerabilities.forEach((vuln, i) => {
      if (doc.y > 650) doc.addPage();
      
      const severityColors = { critical: '#ef4444', high: '#f97316', medium: '#eab308', low: '#3b82f6', info: '#6b7280' };
      doc.fontSize(12).fillColor(severityColors[vuln.severity] || '#475569')
        .text(`${i + 1}. [${vuln.severity.toUpperCase()}] ${vuln.title}`);
      doc.fontSize(9).fillColor('#475569');
      if (vuln.url) doc.text(`URL: ${vuln.url}`);
      if (vuln.description) doc.text(`Description: ${vuln.description}`);
      if (vuln.cvss_score) doc.text(`CVSS Score: ${vuln.cvss_score}`);
      if (vuln.cwe_id) doc.text(`CWE: ${vuln.cwe_id}`);
      if (vuln.remediation) {
        doc.fillColor('#059669').text(`Remediation: ${vuln.remediation}`);
      }
      doc.moveDown();
    });
  }

  // Footer
  doc.fontSize(8).fillColor('#94a3b8').text(`Generated by WebFort v1.0.0 | ${new Date().toISOString()}`, { align: 'center' });
  doc.end();
});

// Generate CSV report
router.get('/:scanId/csv', authenticate, (req, res) => {
  const scan = db.prepare('SELECT * FROM scans WHERE id = ? AND user_id = ?').get(req.params.scanId, req.user.id);
  if (!scan) return res.status(404).json({ error: 'Scan not found' });

  const vulnerabilities = db.prepare(
    'SELECT * FROM vulnerabilities WHERE scan_id = ? ORDER BY cvss_score DESC'
  ).all(req.params.scanId);

  const headers = ['Severity', 'Title', 'Type', 'URL', 'Parameter', 'CVSS Score', 'CWE', 'Description', 'Remediation'];
  const rows = vulnerabilities.map(v => [
    v.severity, v.title, v.type, v.url || '', v.parameter || '',
    v.cvss_score, v.cwe_id || '', (v.description || '').replace(/"/g, '""'), (v.remediation || '').replace(/"/g, '""')
  ]);

  const csv = [headers.join(','), ...rows.map(r => r.map(c => `"${c}"`).join(','))].join('\n');
  res.setHeader('Content-Type', 'text/csv');
  res.setHeader('Content-Disposition', `attachment; filename=webfort-report-${scan.id.slice(0, 8)}.csv`);
  res.send(csv);
});

// Generate SARIF report
router.get('/:scanId/sarif', authenticate, (req, res) => {
  const scan = db.prepare('SELECT * FROM scans WHERE id = ? AND user_id = ?').get(req.params.scanId, req.user.id);
  if (!scan) return res.status(404).json({ error: 'Scan not found' });

  const vulnerabilities = db.prepare(
    'SELECT * FROM vulnerabilities WHERE scan_id = ?'
  ).all(req.params.scanId);

  const severityToLevel = { critical: 'error', high: 'error', medium: 'warning', low: 'note', info: 'none' };

  const sarif = {
    $schema: 'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
    version: '2.1.0',
    runs: [{
      tool: {
        driver: {
          name: 'WebFort',
          version: '1.0.0',
          informationUri: 'https://webfort.io',
          rules: [...new Set(vulnerabilities.map(v => v.type))].map(type => ({
            id: type,
            name: type,
            shortDescription: { text: `${type} vulnerability detection` }
          }))
        }
      },
      results: vulnerabilities.map(v => ({
        ruleId: v.type,
        level: severityToLevel[v.severity] || 'warning',
        message: { text: v.description || v.title },
        locations: v.url ? [{
          physicalLocation: {
            artifactLocation: { uri: v.url }
          }
        }] : []
      }))
    }]
  };

  res.setHeader('Content-Type', 'application/json');
  res.setHeader('Content-Disposition', `attachment; filename=webfort-report-${scan.id.slice(0, 8)}.sarif`);
  res.json(sarif);
});

export default router;
