apiVersion: v1
kind: Secret
metadata:
  name: websecure-secrets
  namespace: websecure
type: Opaque
stringData:
  JWT_SECRET: "change-me-in-production-use-a-32-char-random-string"
  DB_PASSWORD: "websecure_password"
  RABBITMQ_PASSWORD: "websecure_mq"
  SMTP_USER: "user"
  SMTP_PASS: "pass"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: websecure-config
  namespace: websecure
data:
  NODE_ENV: "production"
  PORT: "3001"
  DB_HOST: "postgres"
  DB_USER: "websecure_user"
  DB_NAME: "websecure_db"
  DB_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  RABBITMQ_URL: "amqp://websecure:websecure_mq@rabbitmq:5672/websecure"
  CORS_ORIGIN: "https://websecure.io"
  FRONTEND_URL: "https://websecure.io"
